# Generated by Django 2.2.12 on 2020-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='BlogPost',
        ),
    ]
