# Generated by Django 2.2.12 on 2020-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200528_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('addDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
