# Generated by Django 2.2.12 on 2020-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvelem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvelem',
            name='title',
        ),
        migrations.AddField(
            model_name='cvelem',
            name='type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
    ]
