# Generated by Django 2.2.12 on 2020-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200608_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvelem',
            name='type',
            field=models.CharField(choices=[('1', 'Work Experience'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
    ]
