# Generated by Django 2.2.12 on 2020-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200608_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvelem',
            name='type',
            field=models.CharField(choices=[('1', 'Work Experience'), ('2', 'Education'), ('3', 'Projects'), ('4', 'Certification')], default='1', max_length=20),
        ),
    ]
